---

name: Api code styles & tests.
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  api_ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.8"]
        mongodb-version: ['4.4']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and start mongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependancies
        run: |
          cd api
          python3 -m pip install --upgrade pip
          python3 -m venv .venv && source .venv/bin/activate
          pip install -r requirements.txt

      - name: Check codestyle
        run: cd api && pycodestyle *.py **/*.py **/**/*.py

      - name: Run tests.
        run: |
             cd api && pytest
